import type { TournamentConfig } from '../types/domain';
import { mapParse } from '../utils/MapUtil.ts';

export const AustinMajorSwissConfig: TournamentConfig = {
  id: 'blast_austin_2025',
  name: 'BLAST.TV Austin Major 2025',

  // 初始的16支队伍
  participants: [
    {
      id: 't1',
      name: 'Team Vitality',
      seed: 1,
      logoUrl: '/logos/Vitality.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't2',
      name: 'MOUZ',
      seed: 2,
      logoUrl: 'logos/Mouz.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't3',
      name: 'Spirit',
      seed: 3,
      logoUrl: 'logos/Spirit.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't4',
      name: 'G2',
      seed: 4,
      logoUrl: 'logos/G2.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't5',
      name: 'The MongolZ',
      seed: 5,
      logoUrl: 'logos/TheMongolz.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't6',
      name: 'Aurora',
      seed: 6,
      logoUrl: 'logos/Aurora.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't7',
      name: 'Natus Vincere',
      seed: 7,
      logoUrl: 'logos/Navi.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't8',
      name: 'Liquid',
      seed: 8,
      logoUrl: 'logos/Liquid.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't9',
      name: 'Legacy',
      seed: 9,
      logoUrl: 'logos/Legacy.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't10',
      name: 'Virtus.pro',
      seed: 10,
      logoUrl: 'logos/VP.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't11',
      name: 'paiN',
      seed: 11,
      logoUrl: 'logos/Pain.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't12',
      name: '3DMAX',
      seed: 12,
      logoUrl: 'logos/3DMAX.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't13',
      name: 'FURIA',
      seed: 13,
      logoUrl: 'logos/Furia.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't14',
      name: 'FaZe',
      seed: 14,
      logoUrl: 'logos/Faze.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't15',
      name: 'Nemiga',
      seed: 15,
      logoUrl: 'logos/Nemiga.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't16',
      name: 'Lynn Vision',
      seed: 16,
      logoUrl: 'logos/LVG.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
  ],

  // 阶段定义
  stages: [
    {
      id: 'stage_3_swiss',
      name: 'Opening Stage - Swiss',
      format: 'swiss',
      swiss: {
        winsToAdvance: 3,
        lossesToEliminate: 3,
        rankingStrategy: 'buchholz',

        pairingStrategies: {
          1: 'seed_1v9',
          2: 'seed_greedy',
          3: 'buchholz',
          4: 'buchholz',
          5: 'buchholz',
        },
      },
      results: mapParse(
        `{"__type":"Map","data":[[1,{"__type":"Map","data":[["R1-P0-0-M1","t9"],["R1-P0-0-M2","t10"],["R1-P0-0-M3","t3"],["R1-P0-0-M4","t12"],["R1-P0-0-M5","t13"],["R1-P0-0-M8","t16"]]}],[2,{"__type":"Map","data":[["R2-P1-0-M2","t13"],["R2-P1-0-M4","t10"],["R2-P0-1-M2","t14"]]}],[3,{"__type":"Map","data":[["R3-P1-1-M1","t4"],["R3-P1-1-M2","t14"],["R3-P1-1-M3","t1"]]}],[4,{"__type":"Map","data":[["R4-P1-2-M3","t11"],["R4-P1-2-M1","t2"],["R4-P2-1-M2","t14"],["R4-P2-1-M1","t1"]]}],[5,{"__type":"Map","data":[["R5-P2-2-M1","t11"],["R5-P2-2-M2","t2"],["R5-P2-2-M3","t5"]]}]]}`
      ),
    },
  ],
};
