import type { TournamentConfig } from '../types/domain';

export const AustinMajorSwissConfig: TournamentConfig = {
  id: 'blast_austin_2025',
  name: 'BLAST.TV Austin Major 2025',

  // 初始的16支队伍
  participants: [
    {
      id: 't1',
      name: 'Team Vitality',
      seed: 1,
      logoUrl: '/logos/Vitality.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't2',
      name: 'MOUZ',
      seed: 2,
      logoUrl: 'logos/Mouz.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't3',
      name: 'Spirit',
      seed: 3,
      logoUrl: 'logos/Spirit.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't4',
      name: 'The MongolZ',
      seed: 4,
      logoUrl: 'logos/TheMongolz.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't5',
      name: 'Aurora',
      seed: 5,
      logoUrl: 'logos/Aurora.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't6',
      name: 'Natus Vincere',
      seed: 6,
      logoUrl: 'logos/Navi.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't7',
      name: 'G2',
      seed: 7,
      logoUrl: 'logos/G2.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't8',
      name: 'Liquid',
      seed: 8,
      logoUrl: 'logos/Liquid.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't9',
      name: 'FaZe',
      seed: 9,
      logoUrl: 'logos/Faze.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't10',
      name: 'Virtus.pro',
      seed: 10,
      logoUrl: 'logos/VP.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't11',
      name: 'FURIA',
      seed: 11,
      logoUrl: 'logos/Furia.svg',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't12',
      name: '3DMAX',
      seed: 12,
      logoUrl: 'logos/3DMAX.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't13',
      name: 'Legacy',
      seed: 13,
      logoUrl: 'logos/Legacy.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't14',
      name: 'paiN',
      seed: 14,
      logoUrl: 'logos/Pain.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't15',
      name: 'Lynn Vision',
      seed: 15,
      logoUrl: 'logos/LVG.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't16',
      name: 'Nemiga',
      seed: 16,
      logoUrl: 'logos/Nemiga.webp',
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
  ],

  // 阶段定义
  stages: [
    {
      id: 'stage_3_swiss',
      name: 'Opening Stage - Swiss',
      format: 'swiss',
      swiss: {
        winsToAdvance: 3,
        lossesToEliminate: 3,
        rankingStrategy: 'buchholz',

        pairingStrategies: {
          1: 'seed_1v9',
          2: 'seed_greedy',
          3: 'buchholz',
          4: 'buchholz',
          5: 'buchholz',
        },
      },
    },
  ],
};
