import type { TournamentConfig } from '../types/domain';

/**
 * PGL Copenhagen 2024 (Opening Stage) 的示例配置
 * (队伍是虚构的种子排名)
 */
export const sampleMajorConfig: TournamentConfig = {
  id: 'pgl_copenhagen_2024',
  name: 'PGL Copenhagen 2024 - Opening Stage',

  // 初始的16支队伍
  participants: [
    {
      id: 't1',
      name: 'Team Vitality',
      seed: 1,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't2',
      name: 'FaZe Clan',
      seed: 2,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't3',
      name: 'MOUZ',
      seed: 3,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't4',
      name: 'G2 Esports',
      seed: 4,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't5',
      name: 'Spirit',
      seed: 5,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't6',
      name: 'Natus Vincere',
      seed: 6,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't7',
      name: 'Virtus.pro',
      seed: 7,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't8',
      name: 'Cloud9',
      seed: 8,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't9',
      name: 'HEROIC',
      seed: 9,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't10',
      name: 'Eternal Fire',
      seed: 10,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't11',
      name: 'Complexity',
      seed: 11,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't12',
      name: 'ECSTATIC',
      seed: 12,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't13',
      name: 'The MongolZ',
      seed: 13,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't14',
      name: 'Imperial',
      seed: 14,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't15',
      name: 'paiN Gaming',
      seed: 15,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
    {
      id: 't16',
      name: 'Legacy',
      seed: 16,
      wins: 0,
      losses: 0,
      buchholz: 0,
      playedOpponentIds: [],
    },
  ],

  // 阶段定义
  stages: [
    {
      id: 'stage_1_swiss',
      name: 'Opening Stage - Swiss',
      format: 'swiss',
      swiss: {
        winsToAdvance: 3,
        lossesToEliminate: 3,
        rankingStrategy: 'buchholz',

        pairingStrategies: {
          1: 'seed_1v9',
          2: 'seed_greedy',
          3: 'buchholz',
          4: 'buchholz',
          5: 'buchholz',
        },
      },
    },
  ],
};
